# Root module for the enclave CLI.
# Calls the reusable enclave module.
# Backend is configured in backend.tf (generated by enclave build).

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      ManagedBy  = "opentofu"
      Deployment = var.deployment
      AppName    = var.app_name
    }
  }
}

# The enclave stack: KMS, IAM, VPC, EC2, SSM, S3.
module "enclave" {
  source = "./modules/enclave"

  region            = var.region
  account           = var.account
  deployment        = var.deployment
  app_name          = var.app_name
  instance_type     = var.instance_type
  local             = var.local
  secrets           = var.secrets
  migration_cooldown = var.migration_cooldown
  previous_pcr0     = var.previous_pcr0
  expected_pcr0     = var.expected_pcr0
  supervisor_url          = var.supervisor_url
  github_owner  = var.github_owner
  github_repo   = var.github_repo
  release_tag   = var.release_tag
  github_token  = var.github_token

  eif_path               = var.eif_path
  supervisor_binary_path = var.supervisor_binary_path

  env_values = var.env_values
}

# =============================================================================
# Variables
# =============================================================================

# Root module variables — pass-through to sub-modules.
# These are populated by the Go CLI via terraform.tfvars.json,
# or by company CI pipelines via -var flags or .tfvars files.

variable "region" {
  description = "AWS region for all resources."
  type        = string
}

variable "account" {
  description = "AWS account ID (12 digits)."
  type        = string
}

variable "deployment" {
  description = "Deployment prefix (e.g. dev, staging, prod)."
  type        = string
  default     = "dev"
}

variable "app_name" {
  description = "Application name from enclave.yaml."
  type        = string
}

variable "instance_type" {
  description = "EC2 instance type for the Nitro Enclave host."
  type        = string
  default     = "m6i.xlarge"
}

variable "local" {
  description = "When true, skip VPC/EC2/ECR resources (localstack mode)."
  type        = bool
  default     = false
}

variable "secrets" {
  description = "List of secrets managed by KMS inside the enclave."
  type = list(object({
    name    = string
    env_var = string
  }))
  default = []
}

variable "migration_cooldown" {
  description = "Migration cooldown duration string."
  type        = string
  default     = "0s"
}

variable "previous_pcr0" {
  description = "Previous PCR0 hash for migration chain validation."
  type        = string
  default     = "genesis"
}

variable "expected_pcr0" {
  description = "Expected PCR0 of the current EIF (from pcr.json). Used to trigger migrations."
  type        = string
  default     = ""
}

variable "supervisor_url" {
  description = "Supervisor server URL for local mode migrations."
  type        = string
  default     = "http://localhost:8444"
}

# --- GitHub Release artifacts ---

variable "github_owner" {
  description = "GitHub repository owner (e.g. ArkLabsHQ)."
  type        = string
  default     = ""
}

variable "github_repo" {
  description = "GitHub repository name."
  type        = string
  default     = ""
}

variable "release_tag" {
  description = "GitHub Release tag to fetch artifacts from."
  type        = string
  default     = "eif-latest"
}

variable "github_token" {
  description = "GitHub token for private repo access (optional for public repos)."
  type        = string
  default     = ""
  sensitive   = true
}

# --- Local artifact overrides ---
# When set, these skip the GitHub Release download and use local files directly.
# Used by enclave deploy (CLI builds artifacts locally) and integration tests.

variable "eif_path" {
  description = "Local path to image.eif. Overrides GitHub Release download."
  type        = string
  default     = ""
}

variable "supervisor_binary_path" {
  description = "Local path to supervisor binary. Overrides GitHub Release download."
  type        = string
  default     = ""
}

variable "env_values" {
  description = "Deploy-time overrides for keys declared in app.env (enclave.yaml). Each key/value here is written to SSM at /<deployment>/<app>/env/<key>; the runtime overlays them on top of the EIF's baked defaults at boot. Keys not present in app.env are still written but never read."
  type        = map(string)
  default     = {}
}


# =============================================================================
# Outputs
# =============================================================================

# Root module outputs — re-exported from sub-modules.

output "ec2_role_arn" {
  description = "EC2 instance role ARN."
  value       = module.enclave.ec2_role_arn
}

output "kms_key_id" {
  description = "KMS encryption key ID."
  value       = module.enclave.kms_key_id
  sensitive   = true
}

output "instance_id" {
  description = "EC2 instance ID (empty in local mode)."
  value       = module.enclave.instance_id
}

output "elastic_ip" {
  description = "Static public IP for the enclave instance (empty in local mode)."
  value       = module.enclave.elastic_ip
}

output "storage_bucket" {
  description = "S3 storage bucket name."
  value       = module.enclave.storage_bucket
}

